language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.1"
  - "4.2"
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install libavahi-compat-libdnssd-dev"    
  - "npm install -g grunt-cli bower"
script:
  - "npm test"
  - "grunt dist"
