language: node_js
node_js:
  - 6
  - 8
  - 10
before_install:
  - sudo apt-get update
  - sudo apt-get install libavahi-compat-libdnssd-dev libjpeg-turbo-progs optipng gifsicle
  - npm install -g grunt-cli bower
script:
  - npm test
  - grunt dist
