name: Build
on:
  push:
  pull_request:
  schedule:
    - cron: 26 8 4 * *

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        node_version:
          - 8
          - 10
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: >
          sudo apt -qy update;
          sudo apt -qy install libavahi-compat-libdnssd-dev libjpeg-turbo-progs optipng gifsicle
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: npm install -g grunt-cli bower
      - run: npm install        # this also includes "grunt dist"
      - run: npm test
